sudo: required
services:
  - docker

before_install:
  - pwd && ls -a
  - docker build -t herihakim/server-test -f ./server/Dockerfile.dev .
  - docker build -t herihakim/client-test -f ./client/Dockerfile.dev .

script:
  - docker run herihakim/server-test npm test -- --coverage
  - docker run herihakim/client-test npm test -- --coverage

after_success:
  - docker build -t herihakim/hris_server ./server
  - docker build -t herihakim/hris_client ./client
  - docker build -t herihakim/hris_nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push herihakim/hris_server
  - docker push herihakim/hris_client
  - docker push herihakim/hris_nginx
