version: "3.7"

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: hris_nginx
    ports:
      - "4001:80"

  hris_db:
    image: mongo:4.2.8
    container_name: hris_db
    restart: always
    ports:
      - "27018:27017"

  hris_server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: hris_server
    env_file:
      - .env
    depends_on:
      - hris_db
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app

  hris_client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: hris_client
    env_file:
      - .env
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
