version: "3.7"

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: hris_nginx
    ports:
      - "4001:80"
    networks:
      - hris_network

  hris_db:
    image: mongo:4.2.8
    container_name: hris_db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - type: volume
        source: hris_db_volume
        target: /data/db
    networks:
      - hris_network

  hris_server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: hris_server
    env_file:
      - .env
    depends_on:
      - hris_db
    volumes:
      - type: volume
        source: hris_server_volume
        target: /app/node_modules
      - type: bind
        source: ./server
        target: /app
    networks:
      - hris_network

  hris_client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: hris_client
    stdin_open: true
    env_file:
      - .env
    volumes:
      - type: volume
        source: hris_client_volume
        target: /app/node_modules
      - type: bind
        source: ./client
        target: /app
    networks:
      - hris_network
  
volumes:
  hris_db_volume:
  hris_server_volume:
  hris_client_volume:

networks: 
  hris_network:
    name: hris_network
